apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-chart.fullname" . }}
  labels:
    {{- include "redis-chart.labels" . | nindent 4 }}

spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "redis-chart.selectorLabels" . | nindent 4 }}